import type { ClaimSummary, ComparisonItem, Context, ExperimentItem, MatrixItem, MechanismItem, Perturbation, Project, QuestionItem, Source, Strategy, Transformation } from './types';

export const escape = (value: unknown): string => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char] ?? char);
export const label = (value: string): string => value.replaceAll('_', ' ');
export const KnowledgeKindBadge = (kind: string): string => `<span class="badge ${kind === 'ai_suggestion' ? 'proposal' : ''}">${kind === 'ai_suggestion' ? '◇ ' : '▪ '}${escape(label(kind))}</span>`;
export const ProvenanceBadge = (source: string): string => `<span class="source-tag">↗ ${escape(source)}</span>`;
export const LoadingState = (): string => '<div class="state" role="status">Reading persisted AXIS records…</div>';
export const ErrorState = (message: string): string => `<div class="state error" role="alert"><h2>Workspace unavailable</h2><p>${escape(message)}</p><button data-retry>Try again</button></div>`;
export const EmptyState = (message: string): string => `<div class="state"><span>○</span><p>${escape(message)}</p></div>`;
const stateLabels: Record<string, string> = { evidence_available: '▪ Evidence available', mixed_context_dependent: '⇄ Mixed / context-dependent', limited_evidence: '◐ Limited curated coverage', not_assessed: '○ Not assessed', no_direct_evidence: '○ No direct evidence identified in curated corpus', inconclusive: '? Evidence exists but is inconclusive', contradicts: '≠ Contradictory evidence (explicit assessment)' };
export const EvidenceState = (state: string): string => `<span class="evidence-state ${escape(state)}">${escape(stateLabels[state] ?? label(state))}</span>`;
export const ContextTable = (context: Context): string => `<dl class="context">${Object.entries(context).map(([key, value]) => `<dt>${escape(label(key))}</dt><dd>${escape(value || 'Not reported')}</dd>`).join('')}</dl>`;
export const Transformations = (items: Transformation[]): string => items.map(item => `<details><summary>${escape(item.name)} · v${escape(item.version)}</summary><dl class="context">${item.parameters.map(([key, value]) => `<dt>${escape(label(key))}</dt><dd>${escape(value)}</dd>`).join('')}</dl></details>`).join('');
export const ClaimButton = (claim: ClaimSummary): string => `<button class="claim-button" data-claim="${escape(claim.claim_id)}"><span>${escape(claim.statement)}</span><span class="claim-meta">${KnowledgeKindBadge(claim.knowledge_kind)} ${ProvenanceBadge(claim.source_id)} <span>Inspect evidence →</span></span></button>`;
export const EvidenceMatrix = (items: MatrixItem[]): string => `<div class="matrix">${items.map(item => `<button class="matrix-row" data-domain="${escape(item.domain)}" title="${escape(item.explanation)}"><strong>${escape(item.label)}</strong>${EvidenceState(item.state)}<span>${item.claim_count} claims · ${item.source_count} sources</span><span aria-hidden="true">→</span></button>`).join('')}</div><p class="caption">Coverage states describe this small curated corpus, not systematic literature coverage, confidence or clinical efficacy. Select a domain to inspect its claims.</p>`;
export const MechanismEdge = (item: MechanismItem): string => `<button class="mechanism-edge ${escape(item.assessment.classification)}" data-claim="${escape(item.summary.claim_id)}"><span class="edge-node">${escape(item.claim.subject.label)}</span><span class="edge-line"><span>${escape(label(item.claim.predicate))}</span><b>${item.assessment.classification === 'directly_demonstrated' ? '━━→' : item.assessment.classification === 'inferred' ? '┄┄→' : '···→'}</b><small>${escape(label(item.assessment.classification))}</small></span><span class="edge-node">${escape(item.claim.object.label)}</span><span class="edge-source">${ProvenanceBadge(item.summary.source_id)}<small>Inspect claim + context ↗</small></span></button>`;
export const EvidenceGraph = (items: MechanismItem[]): string => `<div class="graph-legend"><span>━━ Directly demonstrated</span><span>┄┄ Inferred</span><span>··· Hypothesized</span></div><p class="caption">Independent edges in their measured contexts; this is not a demonstrated causal chain to disease.</p><div class="evidence-graph">${items.map(MechanismEdge).join('')}</div>`;
export const ProjectHeader = (project: Project, title: string): string => `<header class="project-header"><div><div class="eyebrow">ERAP1 DISCOVERY PROJECT <span>${project.project_kind === 'curated' ? 'CURATED VERTICAL' : 'DEVELOPMENT FIXTURE'}</span></div><h1>${escape(title)}</h1><p>${escape(project.pair.target.label)} × ${escape(project.pair.disease.label)}</p></div><span class="badge">◌ ${escape(project.project.status)}</span></header><div class="scope"><strong>${project.project_kind === 'curated' ? 'AI-assisted curation · pending expert review' : 'Proposal-only development fixture'}</strong><span>${escape(project.coverage)}</span></div>`;
const nav = [['Overview', 'overview', '◫'], ['Target / Protein', 'protein', '◎'], ['Chemistry', 'chemistry', '⬡'], ['Pharmacology', 'pharmacology', '↔'], ['Selectivity', 'selectivity', '⇄'], ['Cellular Evidence', 'cellular', '▥'], ['Decision', 'decision', '◇'], ['Experiments / Results', 'results', '⚗'], ['Review', 'review', '✓'], ['Retrospective Validation', 'validation', '⏱'], ['Evidence', 'evidence', '▤'], ['Mechanism', 'mechanism', '⌘'], ['Perturbations', 'perturbations', '↔'], ['Strategies', 'strategies', '⇶'], ['Open Questions', 'questions', '?'], ['Next Experiment', 'experiments', '◇']];
export const Sidebar = (projectId: string, route: string): string => `<aside class="sidebar"><a class="brand" href="/home" data-nav><b>AXIS<span>·</span></b><small>Evidence to Therapeutic Decisions</small></a><div class="nav-label">DISCOVERY</div>${[['Home', 'home', '⌂'], ['Projects', 'projects', '▦'], ['Target Explorer', 'targets', '◎']].map(([name, path, icon]) => `<a data-nav href="/${path}" class="nav-item ${route === path ? 'active' : ''}"><span aria-hidden="true">${icon}</span>${name}</a>`).join('')}<div class="nav-label">ACTIVE PROJECT</div>${nav.map(([name, path, icon]) => `<a data-nav href="/projects/${escape(projectId)}/${path}" class="nav-item ${route === path ? 'active' : ''}"><span aria-hidden="true">${icon}</span>${name}</a>`).join('')}<div class="nav-label">DATA</div><a data-nav class="nav-item ${route === 'sources' ? 'active' : ''}" href="/projects/${escape(projectId)}/sources"><span aria-hidden="true">▱</span>Sources</a><div class="sidebar-foot"><span class="local-dot">●</span> Local workspace<small>Read-only · one store owner</small><small>Scientific review required</small></div></aside>`;
export const AppShell = (projectId: string, route: string, content: string): string => `<a class="skip-link" href="#main">Skip to workspace content</a>${Sidebar(projectId, route)}<div class="workspace"><div class="topbar"><span>DISCOVERY <span class="divider">/</span> ERAP1 × axSpA</span><span class="read-only">◉ READ-FIRST WORKSPACE</span></div><main id="main" tabindex="-1">${content}</main><footer>AXIS · Structured evidence, explicit uncertainty · Local reference vertical</footer></div><dialog id="evidence-drawer" aria-labelledby="drawer-title"></dialog>`;
export const StrategyCard = (strategy: Strategy, body: string): string => `<article class="card strategy-card"><div class="card-heading"><h2>${escape(strategy.description)}</h2>${KnowledgeKindBadge(strategy.knowledge_kind)}</div><p>${escape(strategy.rationale)}</p>${body}<h3>Major uncertainty</h3><p>Clinical direction, selective target engagement and genotype / cell-context translation remain unresolved.</p></article>`;
export const OpenQuestionCard = (item: QuestionItem, evidence: string, experiments: string, relationships = ''): string => `<article class="card"><div class="eyebrow">UNRESOLVED SCIENTIFIC QUESTION · ${escape(item.question.status)}</div><h2>${escape(item.question.question)}</h2><h3>Why it matters</h3><p>This open question links the stored evidence to competing intervention strategies and a candidate experiment. Its status remains ${escape(item.question.status)}.</p><h3>Known context limitations</h3>${ContextTable(item.question.scientific_context)}<h3>Evidence informing the question</h3>${evidence}<h3>Relevant perturbations and affected strategies</h3>${relationships || EmptyState('No linked perturbations or strategies in the current read window.')}<h3>Candidate experiment</h3>${experiments}<p class="caption">Linked evidence is bounded to ${item.link_limit} items per category.</p></article>`;
export const ExperimentCard = (item: ExperimentItem): string => `<article class="card experiment-card"><div class="proposal-banner">◇ AXIS SUGGESTION — NOT EXPERIMENTAL EVIDENCE</div><h2>${escape(item.experiment.title)}</h2><h3>Question addressed</h3><a data-nav href="questions">${escape(item.experiment.question_id)} →</a><h3>Rationale</h3><p>${escape(item.experiment.rationale)}</p><h3>Experimental system</h3><p>${escape(item.experiment.experimental_system)}</p><h3>Intervention concept</h3><p>${escape(item.experiment.intervention_description)}</p><h3>Endpoints</h3><p>${escape(item.experiment.endpoint_description)}</p><div class="outcomes">${item.outcomes.map((outcome, index) => `<section><div class="eyebrow">OUTCOME SCENARIO ${String.fromCharCode(65 + index)}</div><p>${escape(outcome.possible_outcome)}</p><h3>Interpretation ${String.fromCharCode(65 + index)}</h3><p>${escape(outcome.interpretation)}</p></section>`).join('')}</div><h3>Unknowns / feasibility constraints</h3><p>System relevance, genotype / allotype strata, selective intervention, controls and feasibility require researcher review. No protocol, compound, dose or observed result has been selected.</p><details><summary>Proposal provenance</summary><p>${escape(item.experiment.provenance.source_identifier)}</p>${Transformations(item.experiment.provenance.transformations)}</details></article>`;
export const SourceCard = (source: Source): string => `<button class="card source-card" data-source="${escape(source.source_id)}"><div>${ProvenanceBadge(source.source_id)} <span class="badge">${escape(label(source.source_kind))}</span></div><h2>${escape(source.title)}</h2><p>${source.claim_count ?? ''} derived claims · retrieved ${escape(source.retrieved_at.slice(0, 10))}</p><span>Inspect source and transformations →</span></button>`;

export const PerformedPerturbationPreview = (items: Perturbation[]): string => '<h3>Performed perturbations</h3>' + (items.filter(item => item.status === 'performed').map(item => `<div class="compact-card perturbation-preview"><strong>${escape(label(item.perturbation_type))}${item.intervention ? ' · ' + escape(item.intervention.label) : ''}</strong><span>${escape(item.scientific_context.experimental_system || 'Not reported')}</span>${item.observed_effect_claim_id ? `<button data-claim="${escape(item.observed_effect_claim_id)}">Inspect observed effect + context →</button>` : '<span>No observed-effect claim linked.</span>'}</div>`).join('') || EmptyState('No performed perturbation in this read window.'));

export function ContextComparison(items: ComparisonItem[]): string {
  const contextRow = (name: string, key: string): [string, (item: ComparisonItem) => string] => [name, item => escape(item.context[key] || 'Not reported')];
  const rows: [string, (item: ComparisonItem) => string][] = [
    ['Atomic assertion', item => ClaimButton(item)],
    ['KnowledgeKind', item => KnowledgeKindBadge(item.knowledge_kind)],
    ['Source', item => `<button data-source="${escape(item.source_id)}">${escape(item.source_id)}</button><p>${escape(item.source.locator || 'Not reported')}</p>`],
    ['Linked performed perturbation', item => item.perturbations.map(value => `${escape(label(value.perturbation_type))} · ${escape(value.status)} · ${escape(value.intervention?.label || 'No named intervention recorded')}`).join('<br>') || 'No perturbation record linked to this exact claim; inspect reported comparison / treatment below.'],
    contextRow('Reported comparison', 'comparison'), contextRow('Reported treatment', 'treatment'),
    contextRow('System', 'experimental_system'), contextRow('Cell type', 'cell_type'),
    contextRow('Genotype', 'genotype'), contextRow('HLA', 'hla_status'),
    contextRow('Allotype', 'allotype'), contextRow('Endpoint', 'endpoint'), contextRow('Assay / readout', 'assay'),
    ['Reported relation / direction', item => escape(label(item.claim.predicate))],
    ['Evidence roles (per subject)', item => item.assessments.map(value => `${EvidenceState(value.role)}<p>${escape(value.strategy_id || value.question_id || '')}</p>`).join('') || 'Not assessed'],
    ['Mechanism classification', item => item.mechanisms.map(value => `<p>${escape(label(value.classification))}</p>`).join('') || 'Not assessed'],
    ['Recorded limitation', item => escape(item.limitation || 'Not reported')]
  ];
  return `<div class="comparison-scroll" tabindex="0" role="region" aria-label="Side-by-side evidence context"><table class="comparison-table"><caption>Original claim contexts and assessments; no automatic contradiction verdict.</caption><thead><tr><th scope="col">Reported field</th>${items.map(item => `<th scope="col">${escape(item.claim_id)}</th>`).join('')}</tr></thead><tbody>${rows.map(([name, value]) => `<tr><th scope="row">${name}</th>${items.map(item => `<td>${value(item)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
}
