import { ContextTable, EmptyState, escape } from './components';
import type { TargetProjection } from './types';

export function SequenceView(sequence: string, title: string): string {
  const rows = sequence.match(/.{1,60}/g) || [];
  return `<section class="section"><h3>${escape(title)}</h3><pre class="protein-sequence" tabindex="0" aria-label="${escape(title)}">${rows.map((row, i) => `${String(i * 60 + 1).padStart(4)}  ${escape(row)}  ${i * 60 + row.length}`).join('\n')}</pre><button data-copy-sequence="${escape(sequence)}">Copy sequence</button><span class="copy-status" role="status"></span></section>`;
}

export function TargetIdentityCard(item: TargetProjection): string {
  const p = item.protein;
  return `<article class="card protein-card"><div class="eyebrow">IMPORTED PROTEIN IDENTITY</div><h2>${escape(p.primary_accession)} · ${escape(p.recommended_name || 'Not reported')}</h2><div class="identity-grid"><section><h3>Gene</h3>${item.mappings.map(m => `<p>${escape(m.gene_namespace)}:${escape(m.gene_entity_id)} — encodes → protein<br>Taxon ${m.taxon_id} · ${escape(m.status)}<br>${escape(m.notes)}</p>`).join('') || EmptyState('No gene mapping imported.')}</section><section><h3>Protein</h3>${ContextTable({ namespace: p.namespace, accession: p.primary_accession, entry: p.entry_name, organism: p.organism_name, taxon: String(p.taxon_id), source_status: p.reviewed_status })}</section><section><h3>Isoform</h3>${item.isoforms.map(i => `<p>${escape(i.accession)} · ${i.canonical ? 'Canonical displayed sequence in this snapshot' : 'Noncanonical annotation'}<br>Sequence: ${i.sequence_length === null ? 'Not imported' : `${i.sequence_length} aa`} · isoform sequence version: ${escape(i.sequence_version ?? 'Not reported')}</p>${i.sequence && !i.canonical ? SequenceView(i.sequence, i.accession) : ''}`).join('') || EmptyState('No explicit isoform identity imported.')}</section><section><h3>Source</h3><button data-protein-source="${escape(p.id)}">${escape(item.snapshot.provider)} · ${escape(p.primary_accession)} · inspect provenance</button><p>Retrieved ${escape(item.snapshot.retrieval_timestamp)}</p></section></div><h3>Canonical sequence in this snapshot</h3><p>${p.sequence_length} aa · entry sequence version ${escape(p.sequence_version ?? 'Not reported')} · record version ${escape(p.record_version ?? 'Not reported')}</p><p class="checksum">Sequence SHA-256: ${escape(p.sequence_checksum)}</p>${SequenceView(p.sequence, 'Displayed entry sequence')}<p>${escape(item.boundary)}</p><h3>Structures</h3>${item.structure_count ? `<button data-structures="${escape(p.id)}">View ${item.structure_count} imported experimental structure(s) →</button>` : EmptyState('No structure records have been imported into AXIS for this target.')}<h3>Chemical matter</h3>${item.chemical_count ? `<a data-nav href="/projects/${encodeURIComponent(item.project_id || '')}/chemistry?protein=${encodeURIComponent(p.id)}">Inspect ${item.chemical_count} chemical identities →</a>` : EmptyState('No chemical-matter records have been imported into this identity layer.')}</article>`;
}

export function ProteinProvenance(item: TargetProjection): string {
  return `<button class="drawer-close" data-close aria-label="Close protein provenance">×</button><h2 id="drawer-title">Protein source snapshot</h2>${ContextTable({ provider: item.snapshot.provider, accession: item.snapshot.provider_record_id, retrieved: item.snapshot.retrieval_timestamp, provider_release: item.snapshot.provider_release, source_record: item.snapshot.request_url, raw_checksum: item.snapshot.raw_content_checksum, sequence_checksum: item.protein.sequence_checksum, importer_version: item.snapshot.importer_version, frozen_resource: item.snapshot.local_resource_path, mapping_status: item.mappings.map(m => m.status).join(', ') || null })}<p>${escape(item.boundary)}</p>`;
}
